In [58]:
import numpy as np
import cv2

In [59]:
img = cv2.imread('./data/irl.jpeg')
cv2.imshow('image',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [60]:
img_shrink = cv2.resize(img,dsize=(320,240),interpolation=cv2.INTER_AREA)

In [61]:
cv2.imshow('image',img_shrink)
cv2.waitKey()
cv2.destroyAllWindows()

In [62]:
#load casscade classifier
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [63]:
#image = img.copy()
image = img_shrink.copy()
#gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.cvtColor(img_shrink, cv2.COLOR_BGR2GRAY)
#apply grayscale image to cascader classifier
face_rect = haar.detectMultiScale(gray)
#draw bounding box
for x,y,w,h in face_rect:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)

cv2.imshow('detected faces',image)
cv2.waitKey()
cv2.destroyAllWindows()

In [29]:
print(face_rect)

[[220 101  77  77]
 [299 127  62  62]
 [150 179  64  64]
 [ 90 141  79  79]
 [550 277  52  52]
 [404 219  73  73]
 [405 148  63  63]]


In [67]:
### Real time face detection using openCV
cap = cv2.VideoCapture('./data/video.mp4')
while True:
    ret,frame = cap.read()
    if ret == False:
        break

    image = frame.copy()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    #apply grayscale image to cascader classifier
    face_rect = haar.detectMultiScale(gray)
    #draw bounding box
    for x,y,w,h in face_rect:
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)
    cv2.imshow('face_detect',image)

    if cv2.waitKey(10) == 27:    #27 is ASCII for escape
        break
cap.release()
cv2.destroyAllWindows()